parameters:
#    common.example.class: GoyGoyEdu\CommonBundle\Example

services:
#    common.example:
#        class: %common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
