person_new:
    path:     /register
    defaults: { _controller: GoyGoyEduPortalBundle:Person:new }
person_login:
    path:     /login
    defaults: { _controller: GoyGoyEduPortalBundle:Person:login }
portal_home:
    path:  /posts
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:index }
post_show:
    path:  /posts/show/{id}
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:show }
post_delete:
    path:  /posts/delete/{id}
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:delete }
post_update:
    path:  /posts/edit/{id}
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:update }
post_new:
    path:  /posts/new
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:insert }
lesson_new_term:
    path:  /lessons/new/term
    defaults: { _controller: GoyGoyEduPortalBundle:Lesson:newterm } 
lesson_new_term2:
    path:  /lessons/new/term/{key}
    defaults: { _controller: GoyGoyEduPortalBundle:Lesson:newterm } 
lesson_new:
    path:  /lessons/new/{key}
    defaults: { _controller: GoyGoyEduPortalBundle:Lesson:new }   
lesson_new2:
    path:  /lessons/new
    defaults: { _controller: GoyGoyEduPortalBundle:Lesson:new }  
lesson_get:
    path:  /lessons/get
    defaults: { _controller: GoyGoyEduPortalBundle:Lesson:get }  
logout:
    path:  /logout
    defaults: { _controller: GoyGoyEduPortalBundle:Person:logout }  