person_new:
    path:     /register
    defaults: { _controller: GoyGoyEduPortalBundle:Person:new }
person_login:
    path:     /login
    defaults: { _controller: GoyGoyEduPortalBundle:Person:login }
portal_home:
    path:  /posts
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:index }
post_show:
    path:  /posts/show/{id}
    defaults: { _controller: GoyGoyEduPortalBundle:Portal:show }