person_new:
    path:     /register
    defaults: { _controller: GoyGoyEduPortalBundle:Person:new }
person_login:
    path:     /login
    defaults: { _controller: GoyGoyEduPortalBundle:Person:login }
