parameters:
#    goy_goy_edu_portal.example.class: GoyGoyEdu\PortalBundle\Example

services:
#    goy_goy_edu_portal.example:
#        class: %goy_goy_edu_portal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
