GoyGoyEdu\PortalBundle\Entity\Department: 
  #repositoryClass: GoyGoyEdu\PortalBundle\Entity\DepartmentRepository
Department:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    term:
      targetEntity: Term
      mappedBy: department
    lesson:
      targetEntity: Lesson
      mappedBy: department
  manyToOne:
    faculty:
      targetEntity: Faculty
      inversedBy: department
      joinColumns:
        faculty_id:
          referencedColumnName: id
