GoyGoyEdu\PortalBundle\Entity\Grades:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    Midterm:
      type: integer
      length: 20
      nullable: true
    Final:
      type: integer
      length: 20
      nullable: true
  manyToOne:
    lesson:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Lesson
      inversedBy: grades
      joinColumns:
        lesson_id:
          referencedColumnName: id
    term:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Term
      inversedBy: grades
      joinColumns:
        term_id:
          referencedColumnName: id
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: grades
      joinColumns:
        person_id:
          referencedColumnName: id
