GoyGoyEdu\PortalBundle\Entity\Lesson:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    grades:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Grades
      mappedBy: lesson
  manyToOne:
    department:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Department
      inversedBy: lesson
      joinColumns:
        department_id:
          referencedColumnName: id
  manyToMany:
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: lesson
      joinTable:
        name: GoyGoyEdu\PortalBundle\Entity\PersonToLesson
        joinColumns:
          lesson_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          person_id:
            referencedColumnName: id
            nullable: false
