GoyGoyEdu\PortalBundle\Entity\PersonToTerm:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    term:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Term
      inversedBy: PersonToTerm
      joinColumns:
        term_id:
          referencedColumnName: id
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: PersonToTerm
      joinColumns:
        person_id:
          referencedColumnName: id

