GoyGoyEdu\PortalBundle\Entity\PersonToLesson:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    type:
      type: integer
      length: 10
      nullable: false
    credit:
      type: integer
      length: 10
      nullable: false
        
  manyToOne:
    term:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Term
      inversedBy: personToLesson
      joinColumns:
        term_id:
          referencedColumnName: id
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: personToLesson
      joinColumns:
        person_id:
          referencedColumnName: id
    lesson:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Lesson
      inversedBy: personToLesson
      joinColumns:
        lesson_id:
          referencedColumnName: id
    department:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Department
      inversedBy: personToLesson
      joinColumns:
        department_id:
          referencedColumnName: id
          
