GoyGoyEdu\PortalBundle\Entity\Person:
  type: entity
  fields:
    id:
      id: true
      type: integer
      length: 4
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
    surname:
      type: string
      length: 255
      nullable: false
    email:
      type: string
      length: 255
      nullable: false
  oneToMany:
    token:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Token
      mappedBy: person
    posts:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Posts
      mappedBy: person
    grades:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Grades
      mappedBy: person
    personToLesson:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\PersonToLesson
      mappedBy: person
    personHasRole:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\PersonHasRole
      mappedBy: person
