GoyGoyEdu\PortalBundle\Entity\PersonHasRole:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: personHasRole
      joinColumns:
        person_id:
          referencedColumnName: id
    role:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Role
      inversedBy: personHasRole
      joinColumns:
        role_id:
          referencedColumnName: id
