GoyGoyEdu\PortalBundle\Entity\Role:
  type: entity
  fields:
    id:
      id: true
      type: integer
      length: 10
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: true
  oneToMany:
    personHasRole:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\PersonHasRole
      mappedBy: role
