GoyGoyEdu\PortalBundle\Entity\Role:
  type: entity
  fields:
    id:
      id: true
      type: integer
      length: 10
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: true
  manyToMany:
    person:
      targetEntity: GoyGoyEdu\PortalBundle\Entity\Person
      inversedBy: role
      joinTable:
        name: GoyGoyEdu\PortalBundle\Entity\PersonHasRole
        joinColumns:
          role_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          person_id:
            referencedColumnName: id
            nullable: false
